def generate_markdown_report(audit_data):
    """
    Converts JSON audit data into a professional Markdown table.
    Perfect for GitHub READMEs or Client Emails.
    """
    header = "## 📜 Legacy Restoration Audit Report\n\n"
    table_header = "| File | Status | Impact Score | Security | Engine Version |\n"
    table_divider = "| :--- | :--- | :--- | :--- | :--- |\n"
    
    rows = ""
    total_impact = 0
    
    for entry in audit_data:
        rows += f"| {entry['file']} | `{entry['status']}` | {entry['impact_score']} | ✅ {entry['security_scan']} | {entry['engine_version']} |\n"
        total_impact += entry['impact_score']

    footer = f"\n**Total Project Impact Points:** {total_impact} pts\n"
    footer += f"\n> *Report generated by Legacy-Code-Archaeology-Engine v1.0*"
    
    return header + table_header + table_divider + rows + footer

# Ejemplo de uso:
# report_md = generate_markdown_report(pipeline_audit_data)
# print(report_md)